AWSTemplateFormatVersion: '2010-09-09'
Description: SSL Zertifikat

# https://docs.aws.amazon.com/de_de/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html

Parameters:
  myDomain:
    Type: String
    Default: apigatewaykurs.de
  mySubDomain:
    Type: String
    Default: "*.apigatewaykurs.de"
  hostedZone:    
    Type: String    
    Default: Z00700000N94O00000000

Resources:  
  mySslCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:             
      DomainName: !Ref myDomain
      DomainValidationOptions:
        - DomainName: !Ref myDomain
          HostedZoneId: !Ref hostedZone      
      SubjectAlternativeNames: 
        - !Ref mySubDomain
      Tags:         
        - Key: project
          Value: api-gateway-course
        - Key: created
          Value: generated
      ValidationMethod: DNS