AWSTemplateFormatVersion: '2010-09-09'
Description: Ein API-Beispiel mit Route 53 Konfiguration - Teil 1

Parameters:
  apiGatewayName:
    Type: String
    Default: domain-test-api-1

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ApiGateway.html

Resources:  
  domainApi:        
    Type: AWS::ApiGateway::RestApi
    Properties:
      Tags:
        - Key: project
          Value: api-gateway-course
        - Key: created
          Value: generated

      Description: Hallo Welt Beispiel mit Domain
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: !Ref apiGatewayName

  rootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId: !GetAtt domainApi.RootResourceId
      RestApiId: !Ref domainApi
      AuthorizationType: NONE
      HttpMethod: GET          
      MethodResponses:
        - StatusCode: '200'                
      Integration:        
        Type: MOCK
        IntegrationHttpMethod: GET      
        IntegrationResponses:
          - StatusCode: '200'            
            ResponseTemplates:            
              'application/json': '{"Message": "Test API mit eigener Domain"}'
        RequestTemplates:
          'application/json': '{"statusCode": 200}'

  apiDeployment:
    Type: AWS::ApiGateway::Deployment    
    DependsOn:
      - rootMethod
    Properties:
      RestApiId: !Ref domainApi
      StageName: develop
      Description: Version 1.0      

Outputs:
  apiGatewayInvokeURL:
    Value: !Sub https://${domainApi}.execute-api.${AWS::Region}.amazonaws.com/develop